name: reharden

on:
  push:
  workflow_dispatch:

jobs:
  reharden:
    strategy:
      fail-fast: false
      matrix:
        project:
          - tt_um_wokwi_411783629732984833
          - tt_um_wokwi_412635532198550529
          - tt_um_wokwi_413385294512575489
          - tt_um_wokwi_413387014781302785
          - tt_um_wokwi_413387093939376129
          - tt_um_wokwi_413387190167208961
          - tt_um_wokwi_group_1
          - tt_um_wokwi_group_2
          - tt_um_wokwi_group_3
          - tt_um_wokwi_group_4
          - tt_um_wokwi_group_5
          - tt_um_wokwi_group_6
          - tt_um_wokwi_group_7
          - tt_um_wokwi_group_8
          - tt_um_wokwi_group_9
          - tt_um_wokwi_group_10
          - tt_um_wokwi_group_11
          - tt_um_wokwi_group_12

    runs-on: ubuntu-24.04
    env:
      OPENLANE_IMAGE_OVERRIDE: htms/openlane2:ihp-v3.0.0.dev17
      PDK_ROOT: ${{ github.workspace }}/pdk
      PDK: ihp-sg13g2
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Checkout tt-support-tools repo
        uses: actions/checkout@v4
        with:
          repository: TinyTapeout/tt-support-tools
          path: wokwi/${{ matrix.project }}/tt
          ref: ttihp25a

      - name: Checkout IHP PDK repo
        uses: actions/checkout@v4
        with:
          repository: TinyTapeout/IHP-Open-PDK
          ref: tt2025
          path: pdk

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        working-directory: wokwi/${{ matrix.project }}
        run: |
          pip install -r tt/requirements.txt

      - name: Install OpenLane (IHP branch)
        shell: bash
        run: |
          pip install https://github.com/TinyTapeout/libparse-python/releases/download/0.3.1-dev1/libparse-0.3.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
          pip install https://github.com/TinyTapeout/openlane2/releases/download/ihp-v3.0.0.dev17/openlane-3.0.0.dev17-py3-none-any.whl

      - name: Fetch verilog and build config
        working-directory: wokwi/${{ matrix.project }}
        shell: bash
        run: ./tt/tt_tool.py --create-user-config --ihp

      - name: Make GDS with OpenLane
        working-directory: wokwi/${{ matrix.project }}
        run: |
          git init
          # tt_tool requires a remote to be set, and some commit to be present
          git remote add origin https://github.com/TinyTapeout/dummy
          git config user.email "bot@github.com"
          git config user.name "Tiny Tapeout Bot"
          git commit --allow-empty -m "Dummy commit"

          python tt/tt_tool.py --create-user-config --harden --ihp

          # Fail if the final GDS file doesn't exist
          if [ ! -f "runs/wokwi/final/gds/${{ matrix.project }}.gds" ]; then
            exit 1
          fi

          # Fail is error.log isn't empty
          if [ -s "runs/wokwi/error.log" ]; then
            exit 1
          fi

      #- name: Publish build logs
      #  #if: failure()
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: GDS_${{ matrix.project }}
      #    path: |
      #      wokwi/${{ matrix.project }}/runs/*

      - name: Install KLayout
        shell: bash
        run: |
          wget https://github.com/TinyTapeout/klayout/releases/download/v0.29.11/klayout_0.29.11-1_amd64.deb
          sudo apt-get update && sudo apt-get install -y ./klayout_0.29.11-1_amd64.deb
          pip install klayout==0.29.11

      - name: Prepare tt_submission artifact
        working-directory: wokwi/${{ matrix.project }}
        shell: bash
        run: |
          mkdir -p tt_submission/stats
          TOP_MODULE=$(./tt/tt_tool.py --print-top-module --ihp)
          cp runs/wokwi/final/commit_id.json tt_submission/
          cp runs/wokwi/final/{gds,lef,spef/*}/${TOP_MODULE}.* tt_submission/
          strm2oas tt_submission/${TOP_MODULE}.gds tt_submission/${TOP_MODULE}.oas
          if [ "$PDK" == "sky130A" ]; then
            cp runs/wokwi/final/pnl/${TOP_MODULE}.pnl.v tt_submission/${TOP_MODULE}.v
          else
            cp runs/wokwi/final/nl/${TOP_MODULE}.nl.v tt_submission/${TOP_MODULE}.v
          fi
          cp runs/wokwi/{OPENLANE_VERSION,PDK_SOURCES,resolved.json} tt_submission/
          cp runs/wokwi/final/metrics.csv tt_submission/stats/metrics.csv
          cp runs/wokwi/*-yosys-synthesis/reports/stat.rpt tt_submission/stats/synthesis-stats.txt

      - name: Publish tt_submission artifact
        uses: actions/upload-artifact@v4
        with:
          name: tt_submission_${{ matrix.project }}
          path: |
            wokwi/${{ matrix.project }}/src/*
            wokwi/${{ matrix.project }}/docs/*
            wokwi/${{ matrix.project }}/tt_submission/*
            wokwi/${{ matrix.project }}/info.yaml
            wokwi/${{ matrix.project }}/LICENSE

